### ISSUE TITLE
Question about use ember-cli-dotenv for other ember addons

### ISSUE THREAD

**Issue by nightire** [fivetanley/ember-cli-dotenv#23]
According to documentation:

> You can then use the node process environment variables in other ember-cli-addons, such as express middleware or other servers/tasks.

It's great, but I don't know how exactly it works, let me explain:

Suppose I'm on developing an addon (or engine in near future), and for sure it will be used in an existed app. The app has already uses ember-cli-dotenv, how addon shares those env variables from target app?

I can imagine like:
1. Use ember-cli-dotenv in addon as well, use same settings as app already had
2. When addon is done, remove ember-cli-dotenv dependency, because app will provide same thing
3. app will install addon, and addon will works as documentation describes

What if addon needs update? install ember-cli-dotenv again and repeat steps above?

I have not do this now, just some assumptions, correct me if wrong and suggestions needed.

**Comment by fivetanley** [comment]
Hi,

These are some great points.

I think ember-cli-dotenv maybe only belongs in the parent application. That way addons only have to rely on environment variables rather than installing this addon. They can share them by using `process.env` in the addon and adding it to the config.js in their addon hooks.
