### ISSUE TITLE
ignore exports in variable defs

### ISSUE THREAD

**Issue by davidkiser** [fivetanley/ember-cli-dotenv#27]
This is really just a feature request,  we typically need exports in our envs that we feed to other systems, and would like to be able to use the same env across systems for simplicity sake.  Right now,  if the .env (what we use on a rails system) contains an 'export' directive,  it will cause ember-cli-dotenv to not pick up the value

So,  this does not work for a .env
export KEY=blah

where this will
KEY=blah

Its not a huge issue,  just forces us to generate 2 seperate envs rather than be able to use a common one with our values

**Comment by fivetanley** [comment]
Hi @davidkiser,

I agree this is a really useful feature and I was surprised to see you had opened this issue. I had assumed [dotenv](https://github.com/motdotla/dotenv) (the library we depend on for .env functionality) did this already, but it turns out they don't.

Unfortunately, it doesn't look like they want to support this functionality either. :( I don't have the time to fork or maintain a fork of dotenv. You can see why they rejected the functionality [in this comment](https://github.com/motdotla/dotenv/pull/118#issuecomment-217648744).

It looks like rails should work without `export` in front of each line by looking at the [original ruby implementation](https://github.com/bkeepers/dotenv#usage). If you remove the `export` I think you'd have a .env that works in both environments.

If that turns out not to be the case, they have a workaround in that comment, which is to use [dotenv-export](https://github.com/AndersDJohnson/dotenv-export) instead.

Sorry for the inconvenience, thanks for opening an issue!
